In [42]:
import numpy as np
from numpy import array, dot, random

# Входные значения
Input = array([[0,0],
            [1,0],
            [0,1],
            [1,1]])

# Ожидаемые выходные значения
Expected_output = array([0,0,0,1])

In [43]:
#Массив со значениями смещений
bias = np.ones((Input.shape[0],1), dtype=int)
bias

array([[1],
       [1],
       [1],
       [1]])

In [44]:
# Добавление к начальному массиву массив bias (массив со значениями смещений)
Input = np.append(Input, bias, axis=1)
Input

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [45]:
# Рандомное распределение весов для значений Input
Weights = random.rand(3)
Weights

array([0.97511217, 0.12847158, 0.92168374])

In [56]:
# Aункция активации
activate_func = lambda sum: 0 if sum < 0 else 1

# скорость обучения
learning_rate = 2e-1 
# количество итераций обучения
N = 200

for i in range(N):
    
    # определения индекса примера из входного массива
    rndm = random.randint(4)
    
    # присвоение значения переменной по сгенерированному индексу
    element_input = Input[rndm]
    expected = Expected_output[rndm]
    
    # произведение входного значения (Х) на вес (W)
    result = dot(W, element_input)
    
    # вычисление ошибки 
    error = expected - activate_func(result)
    
    # изменение весов
    for i in range(len(W)):
        W[i] += learning_rate * error * element_input[i]
print(W)
element_input

[182.41565123 181.84100546 140.12050931]


array([0, 1, 1])

In [55]:
# вывод результата тренировки
for elem in Input:
    result = dot(elem, W)
    print("{}: {} -> {}".format(elem[:2], result, activate_func(result)))

[0 0]: 171.12050930975846 -> 1
[1 0]: 364.1361605411004 -> 1
[0 1]: 362.16151476725946 -> 1
[1 1]: 555.1771659986014 -> 1
