In [26]:
import numpy as np
from numpy import array, dot, random

# Входные значения
Input = array([[0,0],
            [1,0],
            [0,1],
            [1,1]])

# Ожидаемые выходные значения
Expected_output = array([0,0,0,1])

In [27]:
#Массив со значениями смещений
bias = np.ones((Input.shape[0],1), dtype=int)
bias

array([[1],
       [1],
       [1],
       [1]])

In [28]:
# Добавление к начальному массиву массив bias (массив со значениями смещений)
Input = np.append(Input, bias, axis=1)
Input

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [33]:
# Рандомное распределение весов для значений Input
Weights = random.rand(3)
Weights

array([0.4224482 , 0.35601862, 0.21657096])

In [39]:
# Aункция активации
activate_func = lambda sum: 0 if sum < 0 else 1

# скорость обучения
learning_rate = 2e-1 
# количество итераций обучения
N = 200

for i in range(N):
    
    # определения индекса примера из входного массива
    rndm = random.randint(4)
    
    # присвоение значения переменной по сгенерированному индексу
    element_input = Input[rndm]
    expected = Expected_output[rndm]
    
    # произведение входного значения (Х) на вес (W)
    result = dot(W, element_input)
    
    # вычисление ошибки 
    error = expected - activate_func(result)
    
    # изменение весов
    for i in range(len(W)):
        W[i] += learning_rate * error * element_input[i]
print(W)
element_input

[ 0.41565123  0.24100546 -0.47949069]


array([1, 1, 1])

In [40]:
# вывод результата тренировки
for element_x in X:
    result = dot(element_x, W)
    print("{}: {} -> {}".format(element_x[:2], result, activate(result)))

[0 0]: -0.4794906902417356 -> 0
[1 0]: -0.06383945889980042 -> 0
[0 1]: -0.2384852327408417 -> 0
[1 1]: 0.17716599860109344 -> 1
