In [7]:
import torch

#scalar
x = torch.tensor(15)
print(f"Size:-> {x.size()}\n\nTensor:-> {x} \n\nDim:-> {x.ndim}")

Size:-> torch.Size([])

Tensor:-> 15 

Dim:-> 0


In [8]:
#vector
temp = torch.tensor([23,24,24.5,26,27.2,23.0])
print(f"Size:-> {temp.size()}\n\nTensor:-> {temp} \n\nDim:-> {temp.ndim}")

Size:-> torch.Size([6])

Tensor:-> tensor([23.0000, 24.0000, 24.5000, 26.0000, 27.2000, 23.0000]) 

Dim:-> 1


In [9]:
#matrix
from sklearn.datasets import load_boston # выгружаем готовый датасет
boston = load_boston()

boston_tensor = torch.from_numpy(boston.data)
print(f"Size:-> {boston_tensor.size()}\n\nTensor:-> {boston_tensor[:2]}  \n\nDim:-> {boston_tensor.ndim}")

Size:-> torch.Size([506, 13])

Tensor:-> tensor([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
         6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01, 6.4210e+00,
         7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02, 1.7800e+01, 3.9690e+02,
         9.1400e+00]], dtype=torch.float64)  

Dim:-> 2


In [10]:
torch.FloatTensor     #  real
torch.IntTensor       #  integer

torch.IntTensor

In [11]:
#create tensor
tens = torch.FloatTensor([3.2, -5, 2.1, 0.4])
tens

tensor([ 3.2000, -5.0000,  2.1000,  0.4000])

In [12]:
#change tensor type
tens = tens.type_as(torch.IntTensor())
tens

tensor([ 3, -5,  2,  0], dtype=torch.int32)

In [13]:
#create new tens
tens = torch.FloatTensor([[1,2,3], [4,5,6]])
tens

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
# np.reshape() == torch.view()
tens = tens.view(3, 2)
tens

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [15]:
#create tensor without data, but with only size
tens = torch.IntTensor(3, 2, 4)
print(f"Size:-> {tens.size()}\n\nTensor:-> {tens} \n\nDim:-> {tens.ndim}")

Size:-> torch.Size([3, 2, 4])

Tensor:-> tensor([[[1798126768,      32657,   61369472,          0],
         [         0,          0,          0,          0]],

        [[         0,          0,          0,          0],
         [         0,          0,          0,          0]],

        [[         0,          0,          0,          0],
         [         0,          0,          0,          0]]], dtype=torch.int32) 

Dim:-> 3


In [16]:
#zero full
tens_zero = torch.IntTensor(3, 2, 4).zero_()
print(f"Size:-> {tens_zero.size()}\n\nTensor:-> {tens_zero} \n\nDim:-> {tens_zero.ndim}")

Size:-> torch.Size([3, 2, 4])

Tensor:-> tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32) 

Dim:-> 3


In [17]:
# print part of tens with indexing
tens[0, 0:2, 0:2]

tensor([[1798126768,      32657],
        [         0,          0]], dtype=torch.int32)