In [75]:
import numpy as np
from numpy import array, dot, random

Input = array([ [0, 0],
                [0, 1],
                [1, 0],
                [1, 1] ])

Expected_output = array([0, 0, 0, 1])

bias = np.ones((Input.shape[0], 1), dtype=int)
bias

array([[1],
       [1],
       [1],
       [1]])

In [76]:
Input = np.append(Input, bias, axis=1)
Input

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [77]:
#Random values of weights
W = random.rand(3)
W

array([0.44586115, 0.17143987, 0.60354258])

In [87]:
activation_func = lambda sum: 0 if sum < 0 else 1
learning_rate = 2e-1
N_iter = 200


In [100]:
for i in range(N_iter):
    rnd = random.randint(4)
    
    elem = Input[rnd]
    expected = Expected_output[rnd]
    
    result = dot(W, elem)
    
    error = expected - activation_func(result)
    
    for i in range(len(W)):
        W[i] += learning_rate * error * elem[i]
print(W)

[ 0.24586115  0.37143987 -0.39645742]


In [101]:
#Test
for elem in Input:
    result = dot(elem, W)
    print("{}: {} -> {}".format(elem[:2], result, activation_func(result)))

[0 0]: -0.3964574211974223 -> 0
[0 1]: -0.025017550848137726 -> 0
[1 0]: -0.1505962732909888 -> 0
[1 1]: 0.22084359705829576 -> 1
